### ISSUE TITLE
'AsyncAdapt_asyncpg_cursor' object has no attribute 'lastrowid'

### ISSUE THREAD

**Issue by dongfengweixiao** [amisadmin/fastapi_amis_admin#11]
使用 `postgresql+asyncpg` 时，当插入数据时，能够正常写入数据库，但是客户端会提示内部错误，终端提示没有 `lastrowid` 的问题。
![YB0R2~7ZXG){`) H T6G8Y8](https://user-images.githubusercontent.com/1300822/160280222-f1cc2066-a8a8-42f7-82dc-d9fd7d14f51f.png)
AttributeError: 'AsyncAdapt_asyncpg_cursor' object has no attribute 'lastrowid'

如需更多有效信息，请告知

**Comment by amisadmin** [comment]
- postgresql不支持插入的时候获取`lastrowid`, 版本v0.0.21已将此属性默认值`None`.
- sqlalchemy有一个`inserted_primary_key`属性, 但是我尝试没有成功, 如果需要插入数据的时候返回id,你可以研究一下这个属性的用法,提供更好的解决方案.

**Comment by dongfengweixiao** [comment]
版本v0.0.21已修复.
