### ISSUE TITLE
当模型的主键不是用的id,比如自定义成user_id ,设置pk_name后, 可以显示数据,但是编辑更新数据,会报405错误,是接口没有传递item_id参数

### ISSUE THREAD

**Issue by bebee** [amisadmin/fastapi_amis_admin#13]
class Users(SQLModel,table = True):
    user_id: str  =Field(default=None,primary_key=True)
    name: str = Field(title="昵称")
    face_url:str = Field(title='头像')
    gender: int  = Field(title='性别')
    phone_number:Optional[str]  = Field(title='手机号码',default=None)
    birth:datetime = Field(title='生日')
    email:str  = Field(title='用户名')
    ex:Optional[str]= Field(title='扩展字段',default=None)
    create_time:datetime = Field(title='创建时间')
    app_manger_level:int = Field(title='用户等级')
    
@site.register_admin
class UserInfoAdmin(admin.ModelAdmin):
    group_schema = '基本管理'
    page_schema = '用户管理'
    model = Users
    pk_name = 'user_id'

**Comment by bebee** [comment]
我看了代码,目前修复了单独更新删除操作的接口,批量更新和批量删除部分不知道怎么弄,之前那个单独更新接口的参数固定写的“$id" 改成"$pk_name"就可以了,批量更新ids 那个我不知道怎么指定pk_name这个信息了

**Comment by amisadmin** [comment]
> 我看了代码,目前修复了单独更新删除操作的接口,批量更新和批量删除部分不知道怎么弄,之前那个单独更新接口的参数固定写的“$id" 改成"$pk_name"就可以了,批量更新ids 那个我不知道怎么指定pk_name这个信息了

你是对的，这个地方是因为组件渲染的时候固定为$id导致的。ids的修改应该需要查看amis表格这部分的文档。下次更新修复这个问题，感谢你的反馈，欢迎你将你修改的代码部分提交。

**Comment by bebee** [comment]
好的, 我抽空看下amis的文档

**Comment by amisadmin** [comment]
> 好的, 我抽空看下amis的文档

amis的crud组件有一个primaryField属性，是不是直接设置成pk_name就可以了呢？
