### ISSUE TITLE
使用fastapi_user_auth包后,编辑数据的时候原来的Relationship 字段不能选择了,去掉auth 的话又正常

### ISSUE THREAD

**Issue by bebee** [amisadmin/fastapi_amis_admin#14]
你提供的官方的那个例子,改成这样,就会复现
class NewAdminSite(AuthAdminSite):

**Comment by amisadmin** [comment]
可以加入Q群: [229036692](https://jq.qq.com/?_wv=1027&k=U4Dv6x8W) 详情描述一下你遇到的问题

**Comment by bebee** [comment]
好的
