### ISSUE TITLE
依赖需要哪些版本，请给个requirements.txt

### ISSUE THREAD

**Issue by littleforce163** [amisadmin/fastapi_amis_admin#21]
pydantic: v1.6.2
NameError: Field name "fields" shadows a BaseModel attribute; use a different field name with "alias='fields'".

**Comment by littleforce163** [comment]
/pydantic/main.py", line 542, in json
    return self.__config__.json_dumps(data, default=encoder, **dumps_kwargs)
TypeError: 'default' is an invalid keyword argument for this function

**Comment by amisadmin** [comment]
- 请认真查看程序错误提示,这个错误不是依赖问题.
- 相关依赖版本,可以查看[pyproject.toml](https://github.com/amisadmin/fastapi_amis_admin/blob/master/pyproject.toml)
