### ISSUE TITLE
数字选择器上下箭头显示不正确

### ISSUE THREAD

**Issue by woday-dev** [amisadmin/fastapi_amis_admin#26]
### 数字选择器上下箭头乱码

请在**html template里面**添加 css
```
    <link href="https://unpkg.com/amis/sdk/iconfont.css" rel="stylesheet" >
```
具体参考以下link [amis issue link](https://github.com/baidu/amis/issues/3191)

**Comment by amisadmin** [comment]
感谢提供反馈,下个版本更新修复
