### ISSUE TITLE
unpkg太慢了

### ISSUE THREAD

**Issue by woday-dev** [amisadmin/fastapi_amis_admin#27]
经常打开网页有问题，怀疑是网络问题，替换
**https://unpkg.com**
为饿了么国内镜像后飞快，
**https://npm.elemecdn.com**

![image](https://user-images.githubusercontent.com/6330730/172426352-13cfc29d-1038-4fc8-aa21-b6404024599b.png)

**Comment by amisadmin** [comment]
感谢提供反馈,下个版本更新

**Comment by amisadmin** [comment]
可更新版本v0.1.7,通过[Settings](https://docs.gh.amis.work/amis_admin/Settings/#amis_cdn)实例自定义cdn地址
