### ISSUE TITLE
计划什么时候能加上权限

### ISSUE THREAD

**Issue by Chanli52580** [amisadmin/fastapi_amis_admin#3]
计划什么时候能加上权限

**Comment by gitnote-images** [comment]
+1

**Comment by amisadmin** [comment]
当前你可以通过以下两种方法实现权限控制: 

#### 1. 继承重写自定义权限验证方法

- router_permission_depend
- page_permission_depend
- has_page_permission
- has_list_permission
- has_create_permission
- has_read_permission
- has_update_permission
- has_delete_permission



#### 2. 为SiteAdmin对象注册全局权限验证依赖,简单示例如下: 

```python
from fastapi import Depends, FastAPI, Header, HTTPException


async def verify_token(x_token: str = Header(...)):
    if x_token != "fake-super-secret-token":
        raise HTTPException(status_code=400, detail="X-Token header invalid")


async def verify_key(x_key: str = Header(...)):
    if x_key != "fake-super-secret-key":
        raise HTTPException(status_code=400, detail="X-Key header invalid")
    return x_key


site = AdminSite(settings=Settings(debug=True, database_url_async='sqlite+aiosqlite:///admisadmin.db'),
                 fastapi=FastAPI(dependencies=[Depends(verify_token), Depends(verify_key)]))

```



#### 用户认证与授权系统

正在开发当中, 目前大概完成70%左右, 发布时间暂时不确定,可能在3月份吧, 优先体验内测版本,可以加入Q群: [229036692](https://jq.qq.com/?_wv=1027&k=U4Dv6x8W)

**Comment by testyao** [comment]
> 计划什么时候能加上权限

+1

**Comment by amisadmin** [comment]
`FastAPI-Amis-Admin`的用户认证与授权系统请结合[FastAPI-User-Auth](https://github.com/amisadmin/fastapi_user_auth)项目.目前已经可以适用于绝大多数场合,关于权限控制的详细文档,将在后续慢慢补充完善.
