### ISSUE TITLE
请教：fastapi-sqlmodel-crud 怎么使用？ 

### ISSUE THREAD

**Issue by zinohome** [amisadmin/fastapi_amis_admin#37]
class Article(SQLModel, table=True):
    id: int = Field(default=None, primary_key=True, nullable=False)
    title: str = Field(title='ArticleTitle', max_length=200)
    description: Optional[str] = Field(default='', title='ArticleDescription', max_length=400)
    status: bool = Field(None, title='status')
    content: str = Field(title='ArticleContent')

article_crud = SQLModelCrud(model=Article, engine=engine).register_crud()

我想用的model的主键字段不是id，需要制定pk_name,请问SQLModelCrud的构造方法应该怎么写？

**Comment by zinohome** [comment]
我的代码：

brandscrud = SQLModelCrud(model=Brands, engine=apiengine.async_connect()).register_crud()

报错：
 File "./apps/admin/dataapis.py", line 18, in <module>
    brandscrud = SQLModelCrud(model=Brands, engine=apiengine.async_connect()).register_crud()
TypeError: __init__() got an unexpected keyword argument 'engine'

**Comment by zinohome** [comment]
修改代码：
brandscrud = SQLModelCrud(Brands, apiengine.async_connect()).register_crud()

报错：
File "/backend/venv/lib/python3.8/site-packages/fastapi_sqlmodel_crud/_sqlmodel.py", line 63, in __init__
    self.pk: InstrumentedAttribute = self.model.__dict__[self.pk_name]
KeyError: 'id'

**Comment by Ly-star-bit** [comment]
class custom_SqlalchemySelector(SqlalchemySelector):
        def __init__(self, model: Type[TableModelT] = None, fields: List[SqlaField] = None) -> None:
            self.model = model or self.model
            assert self.model, "model is None"
            assert hasattr(self.model, "__table__"), "model must be has __table__ attribute."
            # self.pk_name: str = self.pk_name or self.model.__table__.primary_key.columns.keys()[0]
            self.pk_name: str = self.model.__table__.primary_key.columns.keys()[0] or self.pk_name

            self.pk: InstrumentedAttribute = self.model.__dict__[self.pk_name]

                    # 获取所有主键列的名称
            primary_keys = self.model.__table__.primary_key.columns.keys()
            if not primary_keys:
                raise ValueError("No primary key found for the model")

            # 如果是单一主键，则直接使用
            # 如果是组合主键，则根据应用需求进行处理
            if len(primary_keys) == 1:
                self.pk_name = primary_keys[0]
            else:
                # 例如，组合主键的名称可以用下划线连接
                self.pk_name = '_'.join(primary_keys)

            # 对于组合主键，您需要相应地处理 self.pk 的设置
            # 下面是一个简单示例，仅用于演示
            if len(primary_keys) == 1:
                self.pk = self.model.__dict__[self.pk_name]
            else:
                # 对于组合主键，可能需要自定义处理方式
                # 例如，创建一个包含所有主键字段的元组
                self.pk = tuple(self.model.__dict__[key] for key in primary_keys)
            
            
            
            self.parser = self.parser or TableModelParser(self.model)
            fields = fields or self.fields or self.model_insfields
            exclude = self.parser.filter_insfield(self.exclude)
            self.fields = [
                sqlfield
                for sqlfield in self.parser.filter_insfield(fields + [self.pk], save_class=(Label,))
                if sqlfield not in exclude
            ]
            assert self.fields, "fields is None"
            self.list_filter = self.list_filter and self.list_filter.copy() or self.fields
            self.link_models = self.link_models or {}
            """Make sure the value of link_models is an object attribute, not a class attribute."""
            
            
            我这样重写了__init__可以了
