### ISSUE TITLE
UX optimization/proposal for any overlay Dialog

### ISSUE THREAD

**Issue by swelcker** [amisadmin/fastapi_amis_admin#52]
This is just an idea/proposal to optimize the user experience while using the UI. Any overlay dialog title only shows the action type, like `Create` or `Update` etc. I believe it would be helpfull if we add the `page_schema.label` in `admin.admin.py` to it.

                dialog=Dialog(
                    title=_("Create") + " " + _(self.page_schema.label),  # Something like this
                    size=SizeEnum.lg,
                    body=await self.get_create_form(request, bulk=bulk),

**Comment by amisadmin** [comment]
Can you submit a PR? Because I'm currently working on some other new features.

**Comment by swelcker** [comment]
Thought about this too, will do this the upcoming days, thx
