### ISSUE TITLE
在更新 0.2.4 后检查报错

### ISSUE THREAD

**Issue by qwerdvd** [amisadmin/fastapi_amis_admin#54]
![VV%22U13X8_ER)JH}ZDW7_G](https://user-images.githubusercontent.com/105906879/193816023-dacf4c0b-d545-4a7d-820e-97a6bdd763c6.png)
在回退到0.2.3后是没问题的（
系统是ubuntu22.04

**Comment by amisadmin** [comment]
在配置文件指定语言

**Comment by qwerdvd** [comment]
将ubuntu系统字体改为zh_CN并重启后解决
