### ISSUE TITLE
后期新版本可否将每个版本的的requirement.txt文件给上传上来方便旧版本更新升级

### ISSUE THREAD

**Issue by testyao** [amisadmin/fastapi_amis_admin#57]
大佬辛苦，后期新版本可否将每个版本的的requirement.txt文件给上传上来方便旧版本更新升级，避免升级出现一些版本不兼容的错误

**Comment by amisadmin** [comment]
[pyproject.toml](https://github.com/amisadmin/fastapi_amis_admin/blob/master/pyproject.toml)文件中有完整的依赖.
出现版本不兼容问题,一般是`fastapi-user-auth`,`fastapi-scheduler`未及时更新导致的. 
新版本建议稳定一段时间再升级吧,目前精力没办法做太多细化的工作.

**Comment by testyao** [comment]
好的谢谢，我升级完满屏报数据库的错，升级了下sqlalchey到最新版就好了
