### ISSUE TITLE
后续有考虑支持Tortoise ORM吗？

### ISSUE THREAD

**Issue by smomop** [amisadmin/fastapi_amis_admin#7]

**Comment by amisadmin** [comment]
### 暂时不考虑其他ORM支持. 
`FastAPI-Amis-Admin`与`SQLModel`的结合度非常高, 不仅仅是ORM映射,默认的API请求响应数据格式过滤`pydantic`模型都依赖SQLModel, 支持其他ORM库将会使项目变得更加复杂.此外`SQLModel`本身也拥有足够优秀的特性.
- `SQLModel`与`FastAPI`是同一位作者开发, 因此可以非常完美的与FastAPI项目契合,这个也是`SQLModel`开发的初衷.
- `SQLModel`兼容`sqlalchemy`全部功能,几乎可以实现任何复杂的数据库操作.
- 其他特性,建议阅读官方项目文档: https://github.com/tiangolo/sqlmodel

### 怎么在已使用其他ORM的项目中安装`FastAPI-Amis-Admin`
如果你的项目已经使用了其他ORM进行开发, 并不影响你继续安装`FastAPI-Amis-Admin`.
你只需要新增一个包含`SQLModel`数据库表模型的文件,`SQLModel`的模型定义语法非常简洁,这个过程也非常简单.

**Comment by vvanglro** [comment]
> ### 怎么在已使用其他ORM的项目中安装`FastAPI-Amis-Admin`
> 如果你的项目已经使用了其他ORM进行开发, 并不影响你继续安装`FastAPI-Amis-Admin`, 也不需要修改之前的任何代码. 你只需要新增一个包含`SQLModel`数据库表模型的文件,`SQLModel`的模型定义语法非常简洁,这个过程也非常简单.

你好, 这个可以有一个很小的示例吗？这将会对已使用其它ORM项目的人来说是一个很好入门的教程, 谢谢了.
