### ISSUE TITLE
[建议]使用amis-python代替fastapi_amis.admin.amis

### ISSUE THREAD

**Issue by liunux4odoo** [amisadmin/fastapi_amis_admin#74]
[amis-python](https://github.com/CMHopeSunshine/amis-python)对fastapi_amis.admin.amis做了一些改进:
- 涵盖amis截至2.3.1版本的所有组件
- 使用jinja2模板，方便扩展
- 支持修改主题

fastapi-amis-admin通过简单的修改即可迁移到amis-python:
1. 将对`BaseAmisModel.amis_dict`和`BaseAmisModel.amis_json`两个方法的调用修改为`to_dict`和`to_json`，或者增加别名方法也可。
2. 将`Type[Page].amis_html`的调用修改为`Page.render`，或者在`Page`中增加`render`的别名方法。只要注意`template_path`和`template_name`两个参数的不同即可。

**Comment by amisadmin** [comment]
`fastapi_amis.admin.amis`本身就是一个可以独立的库, 目前没有分离出来只是为了方便项目开发.
- 涵盖所有组件,暂时没有增量价值.低频使用的组件可以使用json替代, 精简核心库代码, 高频使用的组件, 提交pr我会更新到项目.
- amis模板改动很少. 使用jinja2没有额外的优势, 还会导致项目增加一个依赖. 如果用户需要使用jinja2只需要重新赋值`Page.amis_html`类方法.
- `fastapi_amis.admin.amis`同样支持修改主题.

**Comment by liunux4odoo** [comment]
> `fastapi_amis.admin.amis`本身就是一个可以独立的库, 目前没有分离出来只是为了方便项目开发.
> 
> * 涵盖所有组件,暂时没有增量价值.低频使用的组件可以使用json替代, 精简核心库代码, 高频使用的组件, 提交pr我会更新到项目.
> * amis模板改动很少. 使用jinja2没有额外的优势, 还会导致项目增加一个依赖. 如果用户需要使用jinja2只需要重新赋值`Page.amis_html`类方法.
> * `fastapi_amis.admin.amis`同样支持修改主题.

也有道理，fastapi-amis-admin用户在自己的项目中通过简单的patch是可以达到目的的。本想着库里能兼容了，就可以稍微省点事。

再次感谢能开发出fastapi-amis-admin这么实用的库。:smile:
