### ISSUE TITLE
执行操作后的数据不显示或操作失败

### ISSUE THREAD

**Issue by cuifengcn** [amisadmin/fastapi_amis_admin#75]
1. 使用 `await auth.create_role_user('admin')` 创建admin用户，用户只在当前session中存在，需要执行 `session.commit()` 才能真正写入。
2. 在管理后台的”用户管理“中新增用户，其他session中已经能查到新增的用户了，从管理后台中查不到（其他所有接口都是这样，增删改后，界面数据不更新，其他session能查到），服务重启后才会刷新。
```
async_db_url = (
    "mysql+asyncmy://{user}:{password}@{host}:{port}/{database}?charset=utf8mb4".format(
        user=settings.mysql.user,
        password=urlquote(settings.mysql.password),
        host=settings.mysql.host,
        port=settings.mysql.port,
        database=settings.mysql.database,
    )
)
async_engine = create_async_engine(
    async_db_url,
    # echo=True,
    pool_pre_ping=True,
    pool_recycle=3600,
    pool_reset_on_return="rollback",
)
auth = Auth(
    db=AsyncDatabase(engine=async_engine),
    user_model=User,
    token_store=JwtTokenStore(secret_key=settings.server.secret_key),
)
site = AuthAdminSite(
    settings=Settings(
        root_path=settings.server.admin_path,
        site_title="后台管理系统",
        language="zh_CN"
    ),
    auth=auth,
    engine=async_engine,
)
```

**Comment by amisadmin** [comment]
首先检查你使用的`sqlalchemy-database`, `fastapi-user-auth`版本是不是最新版本.

另外, 你提供的示例代码中, auth.db和site.db是两个不同的对象, 系统默认只注册site.db中上下文的中间件. auth.db需要你自己添加一个中间件到fastapi应用. 具体的可以查看`sqlalchemy-database`, `fastapi-user-auth`中对应的方法.

**Comment by cuifengcn** [comment]
> 首先检查你使用的`sqlalchemy-database`, `fastapi-user-auth`版本是不是最新版本.
> 
> 另外, 你提供的示例代码中, auth.db和site.db是两个不同的对象, 系统默认只注册site.db中上下文的中间件. auth.db需要你自己添加一个中间件到fastapi应用. 具体的可以查看`sqlalchemy-database`, `fastapi-user-auth`中对应的方法.

谢谢，添加了中间件，请求结束后进行commit就可以了
```python
@app.middleware("http")
async def test(request: Request, call_next):
    response = await call_next(request)
    await auth.db.async_commit()
    return response
```

**Comment by amisadmin** [comment]
> > 首先检查你使用的`sqlalchemy-database`, `fastapi-user-auth`版本是不是最新版本.
> > 另外, 你提供的示例代码中, auth.db和site.db是两个不同的对象, 系统默认只注册site.db中上下文的中间件. auth.db需要你自己添加一个中间件到fastapi应用. 具体的可以查看`sqlalchemy-database`, `fastapi-user-auth`中对应的方法.
> 
> 谢谢，添加了中间件，请求结束后进行commit就可以了
> 
> ```python
> @app.middleware("http")
> async def test(request: Request, call_next):
>     response = await call_next(request)
>     await auth.db.async_commit()
>     return response
> ```

这个不建议这样写. 应该用`sqlalchemy_database`提供的中间件, 它会自动为每个请求创建一个新的session. 你这样使用的都是同一个session.

**Comment by cuifengcn** [comment]
```
app.add_middleware(BaseHTTPMiddleware, dispath=async_database.asgi_dispatch)
```
是这样吗

**Comment by amisadmin** [comment]
是的
