### ISSUE TITLE
ADMINAPP 指定数据源,缓存不更新

### ISSUE THREAD

**Issue by hmxchina** [amisadmin/fastapi_amis_admin#79]
包版本:
fastapi_amis_admin     0.4.0--0.4.3
fastapi_user_auth      0.4.0--0.4.3

1.与其它应用共用数据源，其它应用更新后，获取的数据还是旧数据
2.程序运行一段时间后，会报错：Can't reconnect until invalid transaction is rolled back

目前解决办法：降低包的版本
fastapi_amis_admin     0.3.1
fastapi_user_auth      0.3.0

**Comment by amisadmin** [comment]
参考: https://github.com/amisadmin/fastapi_amis_admin/issues/75

**Comment by hmxchina** [comment]
新版本需要写中间件，但是老版本不需要写中间件，已经在调整代码了，谢谢
